### ISSUE TITLE
Only downloads first topic

### ISSUE THREAD

**Issue by tarnalcock** [VarunBatraIT/organized-edx-download#1]
Hi There,

When I try and download a course, it only downloads the first 'Welcome' topic even though I have entered option 21 'Download all' when prompted.

**Comment by VarunBatraIT** [comment]
Can you please tell me which course are you trying to download? 
Please note that all course videos must be open. Script only logins and find all available videos in course and download them.

What I am sensing is that you are trying to download something which is not yet fully open. Best way is to select 'view archive' courses or perhaps re run when other chapters are getting open.

**Comment by tarnalcock** [comment]
Hi @VarunBatraIT ,

Thanks you for the followup. 

The course is http://courses.edx.org/courses/course-v1:LinuxFoundationX+LFS101x.2+1T2015

I realize now that many of the chapters contain textual information only, I think this is what may be causing it to freak out.

I am able to run videos in chapter 7 so the closed theory may not be so correct. Unless they only opened recently. I did use the normal edx downloader previously and I got about 6 or so videos all lumped together, so I canceled it and got oedx downloader.

**Comment by VarunBatraIT** [comment]
I just downloaded all the videos in chapters using download all option but it didn't follow the sequence. It didn't break either. So I will be looking at the issue. I have also checked that it works very well with "CS191x Quantum Mechanics and Quantum Computation" 
Lets see.

**Comment by VarunBatraIT** [comment]
Hey @tarnalcock 
I am able to download all chapters using Download Them All as well as individual chapters for Linux Introduction. There was of course naming problem while downloading individual chapters which is now fixed. You might want to give it a try and if you can't download then log will be very useful.

**Comment by VarunBatraIT** [comment]
Can't confirm.
