### ISSUE TITLE
reload issue

### ISSUE THREAD

**Issue by achaleus** [VarunBatraIT/organized-edx-download#2]
Hello, while running oeds-dl.py I am getting the below error. I am using python 3.7

Traceback (most recent call last):
  File "oedx-dl1.py", line 53, in <module>
    reload(sys)  # Reload does the trick!
NameError: name 'reload' is not defined

**Comment by VarunBatraIT** [comment]
Hi Achaleus

It is compatible with python2.7 however I recommend you to use https://github.com/coursera-dl/edx-dl

I will be updating readme. 

Reason is quite simple, they have solved the problem of week with folder issues which was the sole purpose of making this script.
